; Script generated by the Inno Setup Script Wizard.

[Setup]
AppName=ZINGSA Attendance Processing
AppVersion=1.0
DefaultDirName={pf}\ZINGSA Attendance Processing
DefaultGroupName=ZINGSA Attendance Processing
UninstallDisplayIcon={app}\card.exe
Compression=lzma
OutputDir=Output
OutputBaseFilename=Setup
SetupIconFile=C:\Users\mshiri\Desktop\CardDesign\logo.ico
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\mshiri\Desktop\CardDesign\dist\card.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\mshiri\Desktop\CardDesign\logo.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\mshiri\Desktop\CardDesign\logo.png"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{group}\ZINGSA Attendance Processing"; Filename: "{app}\card.exe"
Name: "{commondesktop}\ZINGSA Attendance Processing"; Filename: "{app}\card.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\card.exe"; Description: "{cm:LaunchProgram,ZINGSA Attendance Processing}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
Type: files; Name: "{app}\*.*"
